### ISSUE TITLE
problem after upgradiing gitlab 11

### ISSUE THREAD

**Issue by fbitschy** [dolfim/gitlab_user_creator#1]
hello 
after upgrading to gitlab 11, i get a internal ERROR with this : 
 
File "/webapps/gitlab_user_creator/app/run.py", line 160, in index
    flash('Problems when creating the user: {}'.format(r.json()['message']), 'error')
KeyError: 'message'

thanks so much cause this apps is so usefull

**Comment by rmoreas** [comment]
Fixed by PR #2

**Comment by dolfim** [comment]
PR has been merged, thanks @rmoreas
